import React from "react";
import Navbar from "../components/navbar";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type Props = {
  children: React.ReactNode;
};

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Next Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Piravit Chenpittaya{" "}
          <span className={styles.logo}>
            <Image src="" alt="" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Layout;
